name: CI
on:
  push:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install ansible & lint
        run: |
          pip install ansible ansible-lint
      - name: Syntax check
        run: |
          ansible-playbook --syntax-check playbooks/init.yml || true
          ansible-playbook --syntax-check playbooks/system.yml || true
          ansible-playbook --syntax-check playbooks/verify-system.yml || true
      - name: Lint
        run: |
          ansible-lint || true
